### ISSUE TITLE
Multiple parameters allowed on Given Keyword

### ISSUE THREAD

**Issue by perkss** [egg-plant/eggplant#4]

**Comment by dannicolici** [comment]
Hi @perkss 
Very nice idea (and cool project for noobs contribution - like in my case).
Can you please review my PR? Thanks!

**Comment by perkss** [comment]
@dannicolici thanks definitely the idea behind it as to get people learning and not be scared to contribute so thanks for contributing! I will get on your PR as soon as possible.

**Comment by perkss** [comment]
@dannicolici Thanks
